// export const redisMap = [
//   { method: 'move_to', data: [0,17] },
//   { method: 'line_to', data: [0, 10] },
//   { method: 'line_to', data: [24, 0] },
//   { method: 'line_to', data: [26, 0] },
//   { method: 'line_to', data: [50, 10] },
//   { method: 'line_to', data: [50, 12] },
//   { method: 'line_to', data: [26, 22] },
//   { method: 'line_to', data: [24, 22] },
//   { method: 'line_to', data: [0, 12] },

//   { method: 'move_to', data: [50, 12] },
//   { method: 'line_to', data: [50, 17] },
//   { method: 'line_to', data: [26, 27] },
//   { method: 'line_to', data: [24, 27] },
//   { method: 'line_to', data: [0, 17] },

//   { method: 'move_to', data: [48, 18] },
//   { method: 'line_to', data: [50, 19] },
//   { method: 'line_to', data: [50, 21] },
//   { method: 'line_to', data: [26, 31] },
//   { method: 'line_to', data: [24, 31] },
//   { method: 'line_to', data: [0, 21] },
//   { method: 'line_to', data: [0, 19] },
//   { method: 'line_to', data: [2, 18] },

//   { method: 'move_to', data: [50, 21] },
//   { method: 'line_to', data: [50, 26] },
//   { method: 'line_to', data: [26, 36] },
//   { method: 'line_to', data: [24, 36] },
//   { method: 'line_to', data: [0, 26] },
//   { method: 'line_to', data: [0, 21] },

//   { method: 'move_to', data: [48, 27] },
//   { method: 'line_to', data: [50, 28] },
//   { method: 'line_to', data: [50, 30] },
//   { method: 'line_to', data: [26, 40] },
//   { method: 'line_to', data: [24, 40] },
//   { method: 'line_to', data: [0, 30] },
//   { method: 'line_to', data: [0, 28] },
//   { method: 'line_to', data: [2, 27] },

//   { method: 'move_to', data: [50, 30] },
//   { method: 'line_to', data: [50, 35] },
//   { method: 'line_to', data: [26, 45] },
//   { method: 'line_to', data: [24, 45] },
//   { method: 'line_to', data: [0, 35] },
//   { method: 'line_to', data: [0, 30] },

//   { method: 'move_to', data: [44, 11] },
//   { method: 'line_to', data: [36, 14] },
//   { method: 'line_to', data: [28, 11] },
//   { method: 'line_to', data: [36, 8] },
//   { method: 'line_to', data: [44, 11] },
//   { method: 'move_to', data: [36, 8] },
//   { method: 'line_to', data: [36, 14] },
// ];
export const redisMap = [
  { method: 'move_to', data: [0,17] },
  { method: 'line_to', data: [0, 11] },
  { method: 'line_to', data: [25, 1] },
  { method: 'line_to', data: [50, 11] },
  { method: 'line_to', data: [25, 22] },
  { method: 'line_to', data: [0, 11] },

  { method: 'move_to', data: [50, 11] },
  { method: 'line_to', data: [50, 17] },
  { method: 'line_to', data: [25, 28] },
  { method: 'line_to', data: [0, 17] },

  { method: 'move_to', data: [46, 19] },
  { method: 'line_to', data: [50, 21] },
  { method: 'line_to', data: [25, 32] },
  { method: 'line_to', data: [0, 21] },
  { method: 'line_to', data: [4, 19] },

  { method: 'move_to', data: [50, 21] },
  { method: 'line_to', data: [50, 27] },
  { method: 'line_to', data: [25, 38] },
  { method: 'line_to', data: [0, 27] },
  { method: 'line_to', data: [0, 21] },

  { method: 'move_to', data: [46, 29] },
  { method: 'line_to', data: [50, 31] },
  { method: 'line_to', data: [25, 42] },
  { method: 'line_to', data: [0, 31] },
  { method: 'line_to', data: [4, 29] },

  { method: 'move_to', data: [50, 31] },
  { method: 'line_to', data: [50, 37] },
  { method: 'line_to', data: [25, 48] },
  { method: 'line_to', data: [0, 37] },
  { method: 'line_to', data: [0, 31] },

  { method: 'move_to', data: [44, 11] },
  { method: 'line_to', data: [36, 14] },
  { method: 'line_to', data: [28, 11] },
  { method: 'line_to', data: [36, 8] },
  { method: 'line_to', data: [44, 11] },
];
